# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d99a8bf32d321f2eade65cb056b3c1f20407b1874969a115a45cc3f62cd8656a112a495db400c54f4bfcfe8d94583491142e50d2453f67cdd6f53d7018884fa7

test:
  secret_key_base: b18e33ac1833e530ea93b7bc2639320e023f42fbde651705355c2421aed8a57d4cb851abd2dcd7b17dad121b48134f077c57d5e5eb513f7a241178c3ab08d685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
